samples:
  Healthy_demo:
    bam: /path/to/demo/bam/Healthy_GSM1833219_downsampled.sorted.mini.bam
    GC_bias: /path/to/demo/griffin_GC_correction_demo_files/expected_results/Healthy_demo.GC_bias.txt