#griffin_GC_correction.snakefile
#Anna-Lisa Doebley
#Template made 2021-04-06
#Ha Lab
#Fred Hutchinson Cancer Research Center

#################
#GC bias params##
#################
# #SELECT CORRECT REFERENCE GENOME
# #reference genome for alignment, with index files in same folder as .fa file
reference_genome: /path/to/GRCh38.fa

#chrom sizes for the selected reference genome
chrom_sizes: /path/to/Ref/hg38.standard.chrom.sizes

#size range for GC bias
GC_bias_size_range: 15 500 #do all sizes for this step (that way this can be run one time)

#file containing all mapable regions in the genome
#For typical hg38 WGS the correct filter is below
mapable_regions: /path/to/Ref/repeat_masker.mapable.k50.Umap.hg38.bedGraph

#folder with the gc frequencies for all fragment sizes in the mapable regions (must match the mapable_regions)
#For typical hg38 WGS the correct path is below
genome_GC_frequency: /path/to/Ref/genome_GC_frequency

#where the GC bias output will go
out_dir: results

#minimum mapping quality to keep a read
map_quality: 20


